services:
    reverse-proxy:
        image: "jwilder/nginx-proxy:latest"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "./vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "./network_internal.conf:/etc/nginx/network_internal.conf"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        environment:
            - TRUST_DOWNSTREAM_PROXY=false
        restart: "always"
        networks:
            - "proxy-net"
        ports:
            - "80:80"
            - "443:443"

    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            # Use LE staging server by default, comment the line below for production
            ACME_CA_URI: "https://acme-staging-v02.api.letsencrypt.org/directory"
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks:
            - "proxy-net"

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  proxy-net:
    external: true
